### ISSUE TITLE
Add do_screening_combinato to the repository

### ISSUE THREAD

**Issue by wasserverein** [rebrowski/common_analysis_scripts#2]
And once it's in, ...

- change the waveform plots to density plots to make the plotting faster _please_
- do the plotting in a parfor loop (4 or 8 times faster on ynez....)
  - but this is not entirely trivial because temporary filenames will clash (change them....)

If you don't mind, let me create a pull request containing these changes

**Comment by rebrowski** [comment]
plot_responses_combinato.m is added - thx
