### ISSUE TITLE
do_screening_combinato: mogrify called in two places

### ISSUE THREAD

**Issue by wasserverein** [rebrowski/common_analysis_scripts#4]
At the moment, `mogrify` is called inside `plot_responses_combinato.m` and additionally in `do_screening_combinato.m`. Furthermore, the `-density` option is not set in the call in `do_screening_combinato.m`.

**Comment by rebrowski** [comment]
the call of `mogrify` in `do_screening_combinato.m` has been deleted. The outputs form the initial `mogrify` call using the `-density` option in `plot_responses_combinato.m` will hence not be overwritten.
